### ISSUE TITLE
[URGENT] use google-libphonenumber again, because libphonenumber-js can't validate properly

### ISSUE THREAD

**Issue by kkoomen** [typestack/class-validator#1009]
Hi,

Commit [749fb26](https://github.com/typestack/class-validator/commit/749fb26) is doing something bad, which is replacing `google-libphonenumber` with `libphonenumber-js`, and I understand this package is trying to be as small as possible, but `google-libphonenumber` is the only one out there that covers all the phone numbers properly and I can strongly confirm that `libphonenumber-js` does not.

For example, China has different prefixes/ranges such as `159########`, `130########`, `131########`, `132########` etc, but according to [this wikipedia article](https://en.wikipedia.org/wiki/Telephone_numbers_in_China#Mobile_phones) it should not include the 140–144 range. The `google-libphonenumber` is validating this situation properly, while as `libphonenumber-js` does not.

I _highly_ suggest to revert this back and use `google-libphonenumber` again because you're providing a library right now that provides insufficient validation cases.

FYI: NPM v0.12.1 works, v0.12.2 and above doesn't.

**Comment by kkoomen** [comment]
Is there anyone going to care about this urgent issue? Almost reaching 2 weeks and no one didn't pick this up yet.

**Comment by NoNameProvided** [comment]
This has been fixed in develop via https://github.com/typestack/class-validator/commit/bbb5d78e5e33194cb628c5fe7168d1f72d306cd1 and be included in the next release.

If you are still affected please provide a __minimal__ reproducible example showcasing your problem. The example should:

- be as short as possible while clearly showcasing the problem
- has no external dependencies, only this lib
- the expected and actual behavior should be explained

**Comment by kkoomen** [comment]
@zhaokunlong
