### ISSUE TITLE
Nested arrays are validated as if there is only one.

### ISSUE THREAD

**Issue by stovberpv** [typestack/class-validator#1215]
### Description

Nested arrays are validated as if there is only one.

**Minimal code-snippet showcasing the problem**
 

```ts
import "reflect-metadata";
import { plainToClass, Type } from "class-transformer";
import {
  validate,
  IsDefined,
  IsString,
  IsOptional,
  ValidateNested,
} from "class-validator";

class Bar {
  @IsDefined()
  @IsString()
  id!: string;
}

class Foo {
  @IsOptional()
  @ValidateNested({ each: true })
  @Type(() => Bar)
  bar!: Array<Bar>;
}

{
  const plainFoo = {
    bar: [
      {
        id: "baz"
      }
    ]
  };

  const foo = plainToClass(Foo, plainFoo);
  validate(foo).then((errors) => console.log(errors)); // <-- no errors, as expected
}

{
  const plainFoo = {
    bar: [
      [
        [
          {
            id: "baz"
          }
        ]
      ]
    ]
  };

  const foo = plainToClass(Foo, plainFoo);
  validate(foo).then((errors) => console.log(errors)); // <-- there are still no errors, while there should be
}

```

### Expected behavior

Validation should fail with an error if the real object does not match the validation scheme.
As in this case. It is expected that an array of objects will be received, but instead a lot of arrays are received, but only the last one is validated, while the very first one should be validated and an error should occur on it.

### Actual behavior

Validation is successful, regardless of the number of nested arrays.

**Comment by NoNameProvided** [comment]
Cannot reproduce. Working as expected for me.

```ts
import { IsIn, IsNotEmpty, validate, ValidateNested } from 'class-validator';

class MyWrapper {
  @ValidateNested({ each: true })
  children: MyPayload[] = []

}

class MyPayload {
  @IsNotEmpty()
  @IsIn(['a', 'b'])
  value?: string;

  constructor(value?: string) {
    this.value = value;
  }
}

const wrapper = new MyWrapper();

wrapper.children.push(new MyPayload('a'))
wrapper.children.push(new MyPayload('b'))

// Will pass as expected
validate(wrapper).then(console.log);

wrapper.children.push(new MyPayload('invalid'))

// Will fail as expected
validate(wrapper).then(console.log);
```

**Comment by stovberpv** [comment]
@NoNameProvided I'm sorry, but it looks like you tested something completely different from what I described. I gave an example that multiple array nesting is perceived as a level 1 array. And you are testing that there are elements in the array. What's the point of your test?
I have provided a fully working code where it can be seen that when passing an array in an array, the validator does not return an error as it should.

**Comment by braaar** [comment]
Indeed, @stovberpv, here you are having trouble since in the second example, the `bar` field on our `Foo` instance is a nested array containing plain objects at validation time rather than an array of `Bar` class instances. 

Plain objects and arrays don't have any validation metadata and are ignored by `ValidateNested`. I would say that you need to have some kind of pre-processing of the data before it is transformed class instances, so that it in turn can be properly validated. A correctly constructed class is a prerequisite for validation with this library. 

How exactly you want to do this depends a lot on your particular use case. It seems to me that you may want to [flatten](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) your array?

I suggest writing your own Transform method. Something like this:

```ts
export function transformBar(
  params: TransformFnParams,
): Array<Bar> | undefined {
  if (Array.isArray(params.value)) {
    if (params.value.length === 0) {
      return [];
    } else if (params.value.length > 0) {
      const array = params.value;
      const depth = getArrayDepth(array);

      const flat = array.flat(depth);

      return flat.map(object => plainToInstance(Bar, object));
    }
  } else {
    return undefined;
  }
}

// adapted from https://stackoverflow.com/questions/55420156/get-arrays-depth-in-javascript
function getArrayDepth(value: any[] | any): number {
  if (Array.isArray(value)) {
    return 1 + Math.max(0, ...value.map(getArrayDepth));
  }
  return 0;
}
```

Which you can then use like so:

```ts
class Foo {
  @IsOptional()
  @ValidateNested({ each: true })
  @Transform(transformBar)
  bar!: Array<Bar>;
}
```
