### ISSUE TITLE
feature: Meaningful namespaces

### ISSUE THREAD

**Issue by digimbyte** [typestack/class-validator#1291]
### Description
Currently, it is very easy to confuse and use `isString()` vs `IsString()`

### Proposed solution
I'd propose changing the syntax from `IsString` to `String` or `TypeString`
This should help resolve accidental conflicts between `isString()` and `IsString()` **and** have a meaningful difference in the naming convention

**Comment by NoNameProvided** [comment]
The naming is consistent. You must always import the `CamelCase` version. 

However, this will be changed and probably the validator functions itself will not be exposed as part of the public API. However, I have nothing exact yet. 

Closing this for now as `wontfix`, because this will not be changed for just the sake of it.
