### ISSUE TITLE
Help needed: @ValidateNested issue with entities from local installed package

### ISSUE THREAD

**Issue by loadko** [typestack/class-validator#1381]
### Description
`@ValidateNested` works as expected when your entities are in the same project but when you use entites from a package, **installed from directory not from npm**, it doesn't work. I've created this [repository](https://github.com/loadko/tsc-class-validator) to reproduce the issue.

**Minimal code-snippet showcasing the problem**

`packages.json`
```json
{
  ...
  "dependencies": {
    ...
    "tsc-package": "file:../tsc-package"
  },
  ...
}
```

Package `index.ts`
```ts
export class ParentDto {
  @IsString()
  @IsNotEmpty()
  name: string

  @IsArray()
  @ArrayNotEmpty()
  @ValidateNested({ each: true })
  @Type(() => ChildDto)
  children: ChildDto[]
}

export class ChildDto {
  @IsString()
  @IsNotEmpty()
  name: string

  @IsString()
  @IsNotEmpty()
  age: string
}
```
App `index.ts`
```typescript
...
import { ParentDto } from 'tsc-package/dist'
...
const raw = {
  name: 'parent name',
  children: [
    {}
  ]
}
...
const object = plainToClass(ParentDto, raw)
const errors = await validate(object)

console.log('package errors')
console.log(JSON.stringify(errors, null, 2))
````

### Expected behavior
Our console should show:
```typescript
package errors
[
  {
    "target": {
      "name": "parent name",
      "children": [
        {}
      ]
    },
    "value": [
      {}
    ],
    "property": "children",
    "children": [
      {
        "target": [
          {}
        ],
        "value": {},
        "property": "0",
        "children": [
          {
            "target": {},
            "property": "name",
            "children": [],
            "constraints": {
              "isNotEmpty": "name should not be empty",
              "isString": "name must be a string"
            }
          },
          {
            "target": {},
            "property": "age",
            "children": [],
            "constraints": {
              "isNotEmpty": "age should not be empty",
              "isString": "age must be a string"
            }
          }
        ]
      }
    ]
  }
]
```

### Actual behavior
Instead, we get:
```typescript
package errors
[]
```

How can I get this to work? Is this a bug from `class-validator`?

**Comment by NoNameProvided** [comment]
I cannot reproduce with a partial example. Your import paths are not showing and neither is the `package.json` of the imported package.

My guess would be that different versions of `class-transformer` are used in the two packages and as a result, the `node_modules` has multiple `class-validator` packages. 

The DTO has its metadata defined in the `tsc-package` which is stored in 
```
<project-root>/node_modules/tsc-package/node_modules/class-validator
``` 
while your main application validates with metadata from 
```
<project-root>node_modules/class-validator
```

This means you validate with empty metadata and as a result, the validation passes. There are settings that configure this behavior and instead of passing the validation would fail. Please consult the documentation.
