### ISSUE TITLE
fix: critical vulnerability reported by whitesource

### ISSUE THREAD

**Issue by RezaRahmati** [typestack/class-validator#1389]
### Description
Whitesource scanning tool is reporting a high vulnerability issue on class-validator

here is the description from whitesource:

> In TypeStack class-validator 0.10.2, validate() input validation can be bypassed because certain internal attributes can be overwritten via a conflicting name. Even though there is an optional forbidUnknownValues parameter that can be used to reduce the risk of this bypass, this option is not documented and thus most developers configure input validation in the vulnerable default manner. With this vulnerability, attackers can launch SQL Injection or XSS attacks by injecting arbitrary malicious input. NOTE: a software maintainer agrees with the "is not documented" finding but suggests that much of the responsibility for the risk lies in a different product.

![image](https://user-images.githubusercontent.com/10086092/140991210-3a7a3887-87e7-4144-8512-9e6bb0d5c507.png)

![image](https://user-images.githubusercontent.com/10086092/140991419-c1d0f5fa-c772-4899-b8d7-eb9898390ae3.png)

**Comment by shaunek** [comment]
This issue was raised last month in #1342. The [Github issue](https://github.com/advisories/GHSA-fj58-h2fr-3pp2) was initially marked critical and then downgraded to moderate severity. I don't use Whitesource so I can't comment much on it, but I'm not sure why this same vuln would be classified as high severity there while Github downgraded the severity level.

In practical terms what our team did to ensure that usage of class-validator was safe was to follow the instructions - we used the `forbidUnkownValues` parameter, which is an undocumented option of the `ValidatorOptions`. See #438 for more discussion that started a long time ago.

And FYI - this library seems to be in a limbo state in regards to maintenance, I'm seeing no real activity for the past little while. The Nestjs team is so worried about it that they have apparently forked it and are actively maintaining as of the past few weeks (apparently Nestjs relies on this lib and the related class-transformers heavily). I'm not necessarily suggesting anybody jump over to the Nestjs fork but it might be worth looking into. https://www.npmjs.com/package/@nestjs/class-validator

**Comment by IanMoroney** [comment]
For anyone interested in resolving this issue, change to the recently forked (and patched) @nestjs/class-validator package.

```
"@nestjs/class-validator": "^0.13.3"
```

Update your import references too, and you should be good to go 👍

**Comment by shaunek** [comment]
If you are considering using the @nestjs/class-validator fork and you are a Nestjs user:  be aware that if you are using class-validator simply because it is a nestjs peerDependency (and you need to use ValidationPipe or something), simply replacing class-validator with @nestjs/class-validator won't work by itself. See https://github.com/nestjs/nest/issues/8562

**Comment by array-addu** [comment]
@IanMoroney @shaunek I am still getting this vulnerability even after updating @nestjs/class-validator to 0.13.3 like this `    "class-validator": "npm:@nestjs/class-validator@0.13.3"` 
Can you suggest why it's not working for me?

**Comment by braaar** [comment]
> @IanMoroney @shaunek I am still getting this vulnerability even after updating @nestjs/class-validator to 0.13.3 like this ` "class-validator": "npm:@nestjs/class-validator@0.13.3"` Can you suggest why it's not working for me?

I think you should rather ask about this in https://github.com/nestjs/class-validator

**Comment by IanMoroney** [comment]
this could also help @array-addu :
https://github.com/nestjs/nest/issues/8562#issuecomment-1229255745

**Comment by NoNameProvided** [comment]
Please see https://github.com/typestack/class-validator/issues/1422#issuecomment-1317953863 for details and tracking of the issue. 

In short, the provided POC doesn't result in a bypass since at least 2021 October 22. (So for almost a year) but I had trouble marking the vulnerability as patched with the vendors.

> For anyone interested in resolving this issue, change to the recently forked (and patched) @nestjs/class-validator package.

As far as I can tell the package hosted on NestJS is not patched. You don't get the vulnerability alert because it's published under a new name but the code is the same. 

I am closing this issue as a duplicate of the above-linked one.
