### ISSUE TITLE
question: support for validating property as string or string[]

### ISSUE THREAD

**Issue by gabrielnemeth** [typestack/class-validator#1418]
Hi, how could I validate a string or array of strings?

I have in my class:
```
@IsString()
public parameter: string | string[];
```

Is there a way to tell to class-validator that the parameter could be string or array?

**Comment by UrielCh** [comment]
No Answer for a whole year...

## Proper fix

The proper way would be to change `interface ValidationOptions`, replacing `each?: boolean;` by `each?: boolean | "optional";`
then add some changes in `customValidations` and change in 'ValidationExecutor'
and update the error message generation logic.

Please let me know if you think I should try a PR.

## Quick fix
For now, the easiest way is to write your validator:

### File: `IsStringOrStrings.ts`
```typescript
import { buildMessage, ValidateBy, ValidationOptions } from 'class-validator';

export const IS_STRING_OR_STRINGS = 'isStringOrStrings';

/**
 * Checks if value is an integer.
 */
export function isStringOrStrings(val: unknown): boolean {
  if (typeof val === 'string') return true;
  if (!Array.isArray(val)) return false;
  for (const v of val) {
    if (typeof v !== 'string') return false;
  }
  return true;
}

/**
 * Checks if value is an String or a Strings.
 * Do not set each: true, or except if your looking for a string[] or string[][]
 */
export function IsStringOrStrings(validationOptions?: ValidationOptions): PropertyDecorator {
  return ValidateBy(
    {
      name: IS_STRING_OR_STRINGS,
      validator: {
        validate: (value: unknown /*, args*/): boolean => isStringOrStrings(value),
        defaultMessage: buildMessage((eachPrefix) => eachPrefix + '$property must be a string of string array', validationOptions),
      },
    },
    validationOptions,
  );
}
```

**Comment by NoNameProvided** [comment]
Yes, we have a way, as for any by default unsupported scenario you can define a custom decorator. 

For me, this scenario falls into the "custom needs" category. We cannot add support for every permutation of validation needs because then the lib turns into a big blob of mess. I also don't consider multiple types on the same property a good way to do things only when it's polymorphism with classes. (Still, not my favorite but I understand the need.) 

I am curious about the use-case why simply having `string[]` is not enough and using `parameter.length to decide later if the single value has some special handling. 

Closing this as answered.

If you still think there should be built-in support for this, then you can open a [discussion](https://github.com/typestack/class-validator/discussions/categories/feature-ideas) about this feature so the community can discuss.

**Comment by NoNameProvided** [comment]
Also requested in https://github.com/typestack/class-validator/issues/1635

**Comment by UrielCh** [comment]
I commonly get into the following case:

The problem occurs only with QueryString if my param is named `p` of type `string[]`.
The params will work for `GET http://dom/page?p=value1&p=value2`
but not with `GET http://dom/page?p=value1`,
I think it will work with `GET http://dom/page?p[]=value1`, which will be encoded as `GET http://dom/page?p%5B%5D=value1`, but that is too ugly for me, my 👁️ are Ok with the %20, accept the %3C, %3E as they are pretty helpful for CRUD, but I think humankind should not suffer of the `%5B%5D`,

I understand the `big blob of mess` effect, but since my implementation suggestion is explicit on usage and has no side effect on existing usage, I think it's acceptable.

Of course, the cleanest version would be implementing a `@orValidator`, but this one can cause a `big blob of mess` in the code, and its usage will cause massive boilerplate addition in some already overcharged DTO. (I'm using swagger doc in most of my DTO)

**Comment by NoNameProvided** [comment]
Hi @UrielCh! 

Thanks for the reply, please open a new feature request in the discussion tab if you want this feature to land. There the community can iterate and refine the requirements and define the best API surface for it.
