### ISSUE TITLE
feature: Add support for v1 and v2 UUIDs to isUUID()

### ISSUE THREAD

**Issue by rjschineller** [typestack/class-validator#1497]
### Description
A project I'm working with makes heavy use of this package, and we are starting to use v1 UUIDs in certain areas where we need to glean certain time info from the UUID. I would love to be able to use this package to validate v1 and v2 UUIDs as well. 

Luckily `validator.js` has already expanded this functionality to accept type 1 and 2 UUIDS in [ver 13.7.0](https://github.com/validatorjs/validator.js/pull/1848). And the functionality just needs to be expanded here.

### Proposed solution

This should be an easy drop in replacement in [src/decorator/string/IsUUID.ts](https://github.com/typestack/class-validator/blob/8753936e7d738f524ac353a7a6726558ba2198a2/src/decorator/string/IsUUID.ts#L5)

Original:
```ts
export type UUIDVersion = '3' | '4' | '5' | 'all' | 3 | 4 | 5;
```

Modified:
```ts
export type UUIDVersion = '1' | '2' | '3' | '4' | '5' | 'all' | 1 | 2 | 3 | 4 | 5;
```

**Comment by NoNameProvided** [comment]
I have switched to using the official type from `validator` in the `@IsUUID` decorator. However, the typing is not updated yet, once it is you will be able to use 1 and 2 as versions.

If you want to take the updating of things into your own hand, you can do so here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0039ca2aaaf3b372e9664fd2e765a1eba3ca5a46/types/validator/index.d.ts#L1105 (permalink)

I am closing this as done because there is no action to take on our side.
