### ISSUE TITLE
question: Allow property to be an array or plain type

### ISSUE THREAD

**Issue by intsrc** [typestack/class-validator#1635]
**I was trying to...**
Be able to pass the property like an array of strings or just a string value.
```
class GetUsersDTO {
  // @IsArray() | @IsString()
  readonly status;
}
```

**The problem:**
It's not possible even though it's a common use-case

**Comment by NoNameProvided** [comment]
Yes, we have a way, as for any by default unsupported scenario you can define a custom decorator. 

For me, this scenario falls into the "custom needs" category. We cannot add support for every permutation of validation needs because then the lib turns into a big blob of mess. I also don't consider multiple types on the same property a good way to do things only when it's polymorphism with classes. (Still, not my favorite but I understand the need.) 

I am curious about the use-case why simply having `string[]` is not enough and using `parameter.length to decide later if the single value has some special handling. 

Closing this as answered.

If you still think there should be built-in support for this, then you can open a [discussion](https://github.com/typestack/class-validator/discussions/categories/feature-ideas) about this feature so the community can discuss.

**Comment by NoNameProvided** [comment]
Also requested in https://github.com/typestack/class-validator/issues/1418
