### ISSUE TITLE
Auto Validating Action Params Issue

### ISSUE THREAD

**Issue by MHeironimus** [typestack/class-validator#166]
I have a simple example containing the following:

- A simple class that has a property that is decorated with the `@MaxLength` validator:

~~~
import { MaxLength } from "class-validator";

export class ValidationTestInfo {

	@MaxLength(10)
	name: string;
}
~~~

- A controller method with an action parameter that is an instance of that class:

~~~
  @Put("/health/ValidationError")
  postHealthWithValidationErrors(
    @Body() validationTestInfo: ValidationTestInfo,
    @Req() req: Request): Result<HealthInfo> {

    log.info("Testing model validation middleware.");

    const data: HealthInfo = {
      application: this.applicationInfoService.getApplicationInfo()
    };

    return Result.ok(data);
  }
~~~

### Version 0.7.3

When I run my example using class-validator version 0.7.3, everything works as expected.

If I PUT the following to my endpoint (http://localhost:5002/health/ValidationError):

~~~
{
	"name": "This is too long"
}
~~~

I get the following expected result:

~~~
{
    "_statusCode": 400,
    "_errors": [
        "name must be shorter than or equal to 10 characters"
    ]
}
~~~

### Version 0.8.0 or 0.8.1

When I run my example using class-validator version 0.8.0 or 0.8.1, the validation error (i.e. 400 Bad Request) is not thrown.

When I make the same PUT to my endpoint as above using version 0.8.0 or 0.8.1, I get the following result:

~~~
{
    "_statusCode": 200,
    "_data": {
        "application": {
            "name": "class-validator-test",
            "description": "A project for testing various aspects of the typestack/class-validator library.",
            "version": "0.0.8",
            "nodeVersion": "v8.9.1",
            "timestamp": "2018-02-01T03:38:36.909Z",
            "processPid": 8492,
            "platform": "win32",
            "uptimeInSeconds": 242.689
        }
    }
}
~~~

### Example Project

The example project I used to reproduce this issue can be found at [MHeironimus/class-validator-test](https://github.com/MHeironimus/class-validator-test). The [master](MHeironimus/class-validator-test) branch contains the 0.7.3 version and the [version-0.8.1](https://github.com/MHeironimus/class-validator-test/tree/version-0.8.1) branch contains the 0.8.1 version.

**Comment by NoNameProvided** [comment]
Hi @MHeironimus! 

This is not an issue, but how *npm* and *class-validator* works. Let me to explain:

- Every different *class-validator* instance has its own metadata storage
- *npm* resolve different versions of the same package by inserting the older package into it's requesting module. 

So in your case the `node_modules` folder looks like this: 

```
node_modules/
  class-validator@0.8.1
  routing-controllers@0.7.6
    node_modules/
      class-validator@0.7.3
```

While you import your decorators from the top-level *class-validator* instance *routing-controllers* imports it from its own folder. As I mentioned before because *class-validator* instances don't share the same metadata storage they don't know about each other classes.

So basically what's happening is correct. *routing-controller* validates the payload with its *class-validator* version and it passes because there is no constraint specified for it.

You can verify this by doing a manual validation via:

```ts
import { validate } from "class-validator";
// ...

@Put("/health/ValidationError")
  async postHealthWithValidationErrors(
    @Body() validationTestInfo: ValidationTestInfo,
    @Req() req: Request): Promise<Result<HealthInfo>> {

    const errors: any = await validate(validationTestInfo);

    console.error(errors);

    log.info("Testing model validation middleware.");

    const data: HealthInfo = {
      application: this.applicationInfoService.getApplicationInfo()
    };

    return Result.ok(data);
  }
```

This imports your `validate` function from the top-level `class-validator` instance as your decorators, so calling this function will return a validation error as expected.
