### ISSUE TITLE
question: Is there support for validator composition?

### ISSUE THREAD

**Issue by fauxbytes** [typestack/class-validator#1689]
Similar to [Hibernate-validator's @ConstraintComposition](https://docs.jboss.org/hibernate/stable/validator/api/org/hibernate/validator/constraints/ConstraintComposition.html)?

Essentially looking for a DRY [custom decorator](https://github.com/typestack/class-validator#custom-validation-decorators).
Thanks!

**Comment by NoNameProvided** [comment]
Currently, we don't have a specific decorator for this, but you can achieve it via custom decorators because you can call other decorators inside it (as decorators are simple functions).

If this is something you are still interested in, please open a [feature idea discussion](https://github.com/typestack/class-validator/discussions/categories/feature-ideas) so the community can brainstorm, iterate, define the ideal API and reach a consensus about this should work.

Some items to consider:
- how other decorators with multiple inputs handle this currently
- what is the problem with the current solution
- how would an improved solution look like
- how can we handle backward compatibility
- how other frameworks handle this (if applies)

The end goal of the discussion should be to define an elegant solution with consensus from the community.
