### ISSUE TITLE
fix: validators not working with typescript + graphql

### ISSUE THREAD

**Issue by ddbhagat** [typestack/class-validator#1802]
### Description
Not even the simplest and common validations working with typescript and graphql. 

**Minimal code-snippet showcasing the problem**
Eg.
```ts
import { MaxLength } from 'class-validator';
import { Field, InputType } from 'type-graphql';

@InputType({ description: 'Order Input Object' })
export class OrderInput {
  @Field()
  @MaxLength(8)
  orderNumber: string;

  @Field()
  @MaxLength(7)
  departmentNumber: string;
}


```

### Expected behavior
Ideally the graphql request should fail fast when orderNumber and departmentNumber sent under request say are more than 10 characters eg "99999999999999999". but no failures seen.

### Actual behavior
Request is going through without any validation failures.

Versions:
"class-validator": "^0.13.2",
"type-graphql": "^1.1.1"
"@serverless/typescript": "^3.21.0",

**Comment by braaar** [comment]
Please provide a runnable reproduction for this, such as a codesandbox, codepen, stackblitz, etc.

**Comment by krinchai** [comment]
I believe the issue was caused by typegraphql-prisma generated code. The passed in value to the validator is an object `{ set: value }` not an expected value. Below is a possible idea for the solution.
```
# original
export function maxLength(value: unknown, max: number): boolean {
  return typeof value === 'string' && isLengthValidator(value, { min: 0, max });
}

# with changes
export function maxLength(value: unknown, max: number): boolean {
  const v = value.set || value;
  return typeof v === 'string' && isLengthValidator(v, { min: 0, max });
}
```

**Comment by braaar** [comment]
We can't help you with this unless you provide more details. 
It's hard to know what goes wrong when we don't know how you are calling the `validate` function, whether your object is constructed as a class and how you implement the validation errors in your graphql mutation. Please re-submit this issue with more details if you are still having trouble and you are sure the issue stems from `class-validator` itself.

**Comment by braaar** [comment]
**Your issue was closed**
This means that it was not helpful for `class-validator` to keep this issue open. 
 
Issues are tools for improving the project and should be concrete and actionable. If an issue is no longer relevant or is difficult to work with, it will be closed. The project maintainers need to be selective with their attention and time. 

**What now?**
If you need further help using `class-validator` you can ask a question in the [question and answer section of the discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers).

If you are still experiencing an issue, see [our guide](https://github.com/typestack/.github/blob/master/CONTRIBUTING.md#opening-issues) on how to write helpful issues, and submit a new, improved issue.
