### ISSUE TITLE
Does `class-validator` can validate time offset?

### ISSUE THREAD

**Issue by EizFeren** [typestack/class-validator#1807]
I want to validate time offset for `sequelize` timezone option. I know there's option to use IANA timezone names, but as `sequelize` docs says, `For best cross platform performance use the format +/-HH:MM`.

Is there a way to do such check by `class-validator`?

**Comment by NoNameProvided** [comment]
Do you mean the time-zone information in an ISO 8601 date-time string? Like

```
2022-11-23T21:08:46.111+02:00
                       ~~~~~~ this part? 
```

That part is validated by the `@IsISO8601` validator because an invalid date will not pass that validation. 

If you just want to send let's say `+05:00` as a standalone value, then no we don't have a decorator for that. You can write your own custom validator for that.

**Comment by NoNameProvided** [comment]
Closing this as answered.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
