### ISSUE TITLE
If one project have two instance of class-validator, they cannot validate each other.

### ISSUE THREAD

**Issue by XGHeaven** [typestack/class-validator#184]
here is an example, project structure looks like this
```
- node_modules
  - some-package
    - node_modules
      - class-validator (instance 1)
  - class-validator (instance 2)
- app.ts
```

`package-a` provide some function to validate class powered by `class-validator`.

```ts
// package-a
import {validate} from 'class-validator' // use instance 1
export const someValidate = validate
```

```ts
// app.ts
import {someValidate} from 'some-package'
import {validate, IsInt} from 'class-validator' // use instance 2

class A {
  @IsInt()
  name: string
}

const a = new A()
a.name = 'test'

validate(a).then(console.log) // get errors
someValidate(a).then(console.log) // no errors
```

How to solve this problem?

**Comment by 19majkel94** [comment]
You need to register your own container for metadata using `useContainer` at the very beggining of each package entry-file. TypeDI works out of the box.

The solution for this problem would be to store the metadata in global node process scope but not all maintainers agree with it.

**Comment by NoNameProvided** [comment]
There are multiple options here.

One is what 19majkel94 advised to use a container to get the same instance of class-validator across packages. 

The other method is if you are in control of `some-package` then you can specify a range instead of an explicit version in both package like `0.x` (`^0.8` won't work here, because we are below haven't reached 1.x so minors are considered major by npm). This will flattern you dependencies if you use the latest at least npm@5.x into this: 

```
- node_modules
  - some-package (requires class-validator@0.x)
  - class-validator (class-validator@0.x used by both package)
- app.ts (requires class-validator@0.x)
```

**Comment by vlapo** [comment]
@XGHeaven Did you resolve your issue?

**Comment by XGHeaven** [comment]
@vlapo Yes. I closed.
