### ISSUE TITLE
fix: nested validation produce empty validationErrors

### ISSUE THREAD

**Issue by kannanhassouna** [typestack/class-validator#1856]
### Description
I'm trying to validate an array of nested objects, the validation works perfectly but the validationErrors is empty.

**Minimal code-snippet showcasing the problem**

```
export class CreateUserDto {

  @IsArray()
  @ValidateNested({ each: true })
  @ArrayMinSize(1)
  @Type(() => Hobby)
    hobbies: Hobby[];
}
```

### Expected behavior
```ts 
{
    "name": "Error",
    "statusCode": 400,
    "code": "VALIDATION_ERROR",
    "validationErrors": {
      'hobbies.name': 'hobbies.name must be string'
    }
}
```
### Actual behavior
```
{
    "name": "Error",
    "statusCode": 400,
    "code": "VALIDATION_ERROR",
    "validationErrors": {}
}
```

**Comment by braaar** [comment]
Can you provide a fully runnable reproduction? How are you calling the validate function? How are you constructing your class instance?

**Comment by braaar** [comment]
It seems to work fine for me.

Your Hobby class may look different, but here is my basic interpretation:
```ts
import { plainToClass, Type } from 'class-transformer';
import {
  ArrayMinSize,
  IsArray,
  IsString,
  validate,
  ValidateNested,
} from 'class-validator';

export class Hobby {
  @IsString()
  name: string;
}

export class CreateUserDto {
  @IsArray()
  @ValidateNested({ each: true })
  @ArrayMinSize(1)
  @Type(() => Hobby)
  hobbies: Hobby[];
}

const plainObject = {
  hobbies: [{ name: 1234 }],
};

const errors = await validate(plainToClass(CreateUserDto, plainObject));

console.log(JSON.stringify(errors, null, 2));
```
Note: You can't use top level await unless you are using [ESM](https://nodejs.org/api/esm.html#modules-ecmascript-modules).

Here's the output:
```json
[
  {
    "target": {
      "hobbies": [
        {
          "name": 1234
        }
      ]
    },
    "value": [
      {
        "name": 1234
      }
    ],
    "property": "hobbies",
    "children": [
      {
        "target": [
          {
            "name": 1234
          }
        ],
        "value": {
          "name": 1234
        },
        "property": "0",
        "children": [
          {
            "target": {
              "name": 1234
            },
            "value": 1234,
            "property": "name",
            "children": [],
            "constraints": {
              "isString": "name must be a string"
            }
          }
        ]
      }
    ]
  }
]
```

**Comment by braaar** [comment]
You may have some trouble passing the validation error along to your API endpoint, by the looks of it. 

That is outside the scope of class-validator. I would guess you need to put a `return` instead of a `throw` somewhere.

**Comment by braaar** [comment]
**Your issue was closed**
This means that it was not helpful for `class-validator` to keep this issue open. 
 
Issues are tools for improving the project and should be concrete and actionable. If an issue is no longer relevant or is difficult to work with, it will be closed. The project maintainers need to be selective with their attention and time. 

**What now?**
If you need further help using `class-validator` you can ask a question in the [question and answer section of the discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers).

If you are still experiencing an issue with class-validator, see [our guide](https://github.com/typestack/.github/blob/master/CONTRIBUTING.md#opening-issues) on how to write helpful issues, and submit a new, improved issue.
