### ISSUE TITLE
question: default value forbidUnknownValues

### ISSUE THREAD

**Issue by aashutoshrathi** [typestack/class-validator#2317]
**I was trying to...**
see if forbidUnknownValues is true by default in 0.14.0

**The problem:**
In docs it still says
`Fails validation for objects unknown to class-validator. Defaults to false`

**Comment by braaar** [comment]
Could you point to the exact file and line you are referring to? I can't seem to find what you are referring to.

**Comment by aashutoshrathi** [comment]
https://github.com/typestack/class-validator/blob/ceb55025e09ed5e5629ff9b3e992533234fb51db/src/validation/ValidatorOptions.ts#L75

**Comment by braaar** [comment]
That is a past version of the source code from a year ago.

**Comment by aashutoshrathi** [comment]
which branch has the latest code?

**Comment by braaar** [comment]
`develop`. I'll consider this issue settled

**Comment by aashutoshrathi** [comment]
> `develop`. I'll consider this issue settled

I might be completely wrong here, but isn't [this](https://github.com/typestack/class-validator/blob/develop/src/validation/ValidatorOptions.ts) the code from develop.

https://github.com/typestack/class-validator/blob/0b50d8db994a3d873e78da11bdd951f020b0ff97/src/validation/ValidatorOptions.ts#L74-L82

And for the context, I'm just talking about doc strings.

Example here _(using v0.14.0):_
<img width="1219" alt="image" src="https://github.com/typestack/class-validator/assets/21199234/4142cd6b-1d1d-482f-906a-e1bc36ca527c">

Thanks for actively replying and apologies for being PITA

**Comment by brnkes** [comment]
I noticed the same discrepancy. Seems like a typo ? 

Changelog (0.14.0) implies that `forbidUnknownValues` is enabled by default & https://github.com/typestack/class-validator/pull/1798 implements a true-by-default logic.

However, `ValidatorOptions`' JSDoc suggests otherwise. https://github.com/typestack/class-validator/commit/e252183849c4312973a3f18b57bf3f15c5ae5719 is the last commit for `ValidatorOptions` and it is also what the most recently published package (0.14.0) includes.

**Comment by braaar** [comment]
I stand corrected! This is indeed a typo.

**Comment by braaar** [comment]
PR welcome :)
