### ISSUE TITLE
class-validator not working as expected after using Container

### ISSUE THREAD

**Issue by LogansUA** [typestack/class-validator#233]
Hi.

So here's the [repository](https://github.com/LogansUA/jest-import-error/tree/class-validator-error) where class-validator is not working as expected

As you can see in [`base-controller.ts`](https://github.com/LogansUA/jest-import-error/blob/class-validator-error/src/api/controllers/base-controller.ts) the reproducible logic with example from README.
The `validate` method returns **empty** array of errors.

But if i'll disable the [`classValidatorUseContainer` in `app.ts`](https://github.com/LogansUA/jest-import-error/blob/class-validator-error/src/app.ts#L48) then validation works.

Any ideas whats wrong with my `Container`?

This thing is really critical for me.

Thank you.

**Comment by NoNameProvided** [comment]
You got an empty array as result because class-validator doesn't found any meta-data related to the recieved class, so there is nothing to validate. I understand this may not be the best behaviour, and actually you can enforce an error when an object is recieved which has no registered metadata with the `forbidUnknownValues` option in the `ValidatorOptions`. After enabling that option you should recieve a `ValidationError` for unknown values.

As you wrote, you got no errors because you use a custom container and while your metadata is registered in your custom container, the class-validator used in routing-controllers will look for it in the default one. 

Why do you want to specify a custom container for class-validator?

**Comment by NoNameProvided** [comment]
> Actually, the only reason why I use custom container because I took this boilerplate for my project.

It's safe to comment that line out until you dont want to use custom validatio classes.

> Would be great to read more about this integration.

You need to use a container if you want to share some dependencies between your custom validator classes and the rest of the application. It's explained in the [documentation](https://github.com/typestack/class-validator#using-service-container).
