### ISSUE TITLE
fix: Typo in Readme file

### ISSUE THREAD

**Issue by itssabhishek** [typestack/class-validator#2494]
### Description
I think there's a type in Usage section of Readme file. 

**Minimal code-snippet showcasing the problem**
```ts
post.text = 'this is a great post about hell world';
```

### Expected behavior
Instead of **_hell_** it should be **_hello_**

**Comment by 1jinu** [comment]
I think you omitted a very important context that is the comment that follows right after this line.
The full code snippet is:
```TypeScript
post.text = 'this is a great post about hell world'; // should not pass
```
The comment reads "`should not pass`" since it's explaining how the decorator `@Contains('hello')` should not match `'this is a great post about hell world'` since it reads `'hell'` and not `'hello'`.

I looked at all instances of the word 'hell' in the repo and there does not seem to be any typos.

**Comment by dev-brandwick** [comment]
@1jinwoo yeah you're right 
I am really sorry.

**Comment by itssabhishek** [comment]
@1jinwoo you're right 
I didn't get full context.
Sorry for my mistake.
