### ISSUE TITLE
How to remove "weaker" validation?

### ISSUE THREAD

**Issue by lazarljubenovic** [typestack/class-validator#280]
It's easier to explain on an example of validating a body of a request:

```ts
  @IsNotEmpty({
    message: `Password is required.`,
  })
  @MinLength(8, {
    message: `Password must be over 8 characters.`,
  })
  readonly password: string
```

If the endpoint receives `{}`, `{password: null}` or `{password: ''}`, it will return an error which mentions both of these validation errors, which makes an awkward copy in the UI:

```text
Password: ______________
Password is required. Password must have over 8 characters.
```

It could even end up being

```text
Password: ______________
Password must have over 8 characters. Password is required.
```

since there's no ordering on the `constraints` (it's an object, not an array).

I'd like to somehow say that `IsNotEmpty` is "stronger" -- if it fails that validator, it shouldn't even move to others. Alternatively, I'd like to say to skip validating `MinLength` if the value is `undefined`, `null` or `''`.

---

My current workaround is returning an empty error message and then discarding errors which are empty strings on the UI of the SPA.

```ts
  @IsNotEmpty({
    message: `Password is required.`,
  })
  @MinLength(8, {
    message: ({ value }: ValidationArguments) => {
      return value == null || value == ''
        ? ''
        : `Password must be over 8 characters.`
    },
  })
  readonly password: string
```

**Comment by RWOverdijk** [comment]
So how does this work in 2020? 😄

**Comment by braaar** [comment]
**Your issue is being closed**
This means that it was not helpful for `class-validator` to keep this issue open. 
 
Issues are tools for improving the project and should be concrete and actionable. If an issue is no longer relevant or is difficult to work with, it will be closed. The project maintainers need to be selective with their attention and time. 

This issue is vaguely suggesting that some new feature is made, but it's not mature enough to be actionable, and has seen very little activity.

**What now?**
If you still want to discuss this feature, you can create a discussion in the [feature discussion section of the discussions tab](https://github.com/typestack/class-validator/discussions/categories/feature-ideas).

**Comment by NoNameProvided** [comment]
This is not possible at the moment. If you would like to see this implemented you can open a feature idea on the discussion tab. From there the community can iterate on the idea and define what the feature request should be exactly.
