### ISSUE TITLE
Null value passes when skipMissingProperties set to true

### ISSUE THREAD

**Issue by iveselin** [typestack/class-validator#308]
When skipMissingProperties is set to true, if property has null value, it will not validate with IsNotEmpty decorator and null value will be forwarded to controller/service/db repo etc. and cause a crash
[Source of error](https://github.com/typestack/class-validator/blob/master/src/validation/ValidationExecutor.ts#L100)

### Example
Json input
```javascript
{
    "startDate":null 
}
```

Part of UpdateProjectDto
```javascript
 @IsNotEmpty()
 @IsDateString()
 readonly startDate: Date;
```

Nest.js framework controller example of code which will receive poData with startDate set to null and crash at DB query...
```javascript
@Patch('/:id')
@UsePipes(new ValidationPipe({ skipMissingProperties: true }))
    updateById(@Param('id', new ParseIntPipe()) id, @Body() poData: UpdateProjectDto) {
        //#update route
        return this.projectsService.updateById(id, poData);
   }
```

**Comment by nigelthinksprint** [comment]
any idea why this might be anyone?

**Comment by zhenwenc** [comment]
Just search the source code :-) 

```
// ValidationExecutor#execute
...
            if ((value === null || value === undefined) && this.validatorOptions && this.validatorOptions.skipMissingProperties === true) {
                return;
            }
...
```

https://github.com/typestack/class-validator/blob/master/src/validation/ValidationExecutor.ts#L100

**Comment by jumojer** [comment]
I'm having a similar issue.
Why would we consider `null` as equivalent to `undefined` in this case?
I believe this behavior breaks partial object validation for non-nullable fields.

For example:
```javascript
    @IsString()
    @IsNotEmpty()
    @IsDefined()
    name: string;
```
Those two objects would both pass validation when the `skipMissingProperties` is applied
```javascript
validate({}, { skipMissingProperties: true})
validate({ "name": null }, { skipMissingProperties: true})
```
Which, in my case, triggers a database `Column 'name' cannot be null` error.

Wouldn't it make more sense if  `skipMissingProperties` and the `IsDefined` decorators relied solely on whether the property is, well, defined instead of also checking if it is `null`?

**Comment by thomas-ama** [comment]
Some properties of my model can be `null`, some can't. None can be `undefined`.
In case of `PUT` / `PATCH` HTTP requests, I'm using `{ skipMissingProperties: true}` to validate the body of my request because it contains only updated properties.

However:
- `{ skipMissingProperties: true}` doesn't validate `null` values
- `@IsDefined()` makes no differences between `null` and `undefined`
So, it is not possible to validate correctly the request body.

Solutions:
- `skipMissingProperties` could skip only undefined values (but it would introduce breaking changes I guess)
- Add a `skipUndefinedProperties` option (quite easy from what I read)

**Comment by muyu66** [comment]
"skipUndefinedProperties " is right

**Comment by henrikra** [comment]
I really also think that handling null and undefined are handled the same! That is like handling numbers and strings the same 😄

**Comment by henrikra** [comment]
People in this thread go to see the PR that could possibly solve this issue and give it a review! https://github.com/typestack/class-validator/pull/353

**Comment by tocosastalo** [comment]
**temporary solution**

turn off `skipMissingProperties`: `{skipMissingProperties: false}`

and use `@ValidateIf` decorator:
```
@ValidateIf(o => 'name' in o)
@IsString()
@IsNotEmpty()
readonly name?: string;
```

**Comment by vlapo** [comment]
I agree `skipMissingProperties` is little bit misleading. We should introduce `skipUndefinedProperties` and also `skipNullProperties`. `skipMissingProperties` should be deprecated and removed in `1.0` version. What do you think about `skipNullProperties`? Is it useable option?

**Comment by iveselin** [comment]
Yes, in some APIs you want to delete null values, and i some you want to save them. These two options would give us the diversity we need.
