### ISSUE TITLE
IsInstance validation proper usage with typeORM

### ISSUE THREAD

**Issue by kedar-moghe** [typestack/class-validator#390]
I am using typeORM.  Let's say I have the following:

```js
class Owner {
  @PrimaryGeneratedColumn()
  id: number;

  @OneToOne(type => User)
  @JoinColumn({ name: 'user_id' })
  @IsInstance(User)
  user: User;
}

const owner = new Owner();
const user = new User();
user.id = 1;

owner.user = user;

await validate(owner)
```

In this case, I get an error with the message: `isInstance decorator expects and object as value, but got falsy value.`

If I use `validator.isInstance(owner.User, User)`, that returns true.

I looked at the specs and it seems like only the validate.isInstance is tested.  How is IsInstance intended to work?  Thanks

**Comment by vlapo** [comment]
This simple test give me no validation errors. Could you provide simple failing test case?

```ts
import 'reflect-metadata';
import { IsNotEmpty, IsString, validateSync, IsDecimal, IsInstance, validate } from 'class-validator';
import { plainToClass } from 'class-transformer'; 

class User {}

class Owner {
  id: number;

  @IsInstance(User)
  user: User;
}

const owner = new Owner();
const user = new User();

owner.user = user;

validate(owner).then(err => console.log(err));
```

**Comment by lipsumar** [comment]
I'm having a similar issue, only when running in jest. Seems related to [this](https://github.com/typeorm/typeorm/issues/850)

I can reproduce the error `isInstance decorator expects and object as value, but got falsy value.` by providing the decorator with `@IsInstance(undefined)` instead of `@IsInstance(User)`.

When running in jest, if i console.log User, i'll get undefined - where it should obviously be the User class. This seems like a circular dependency issue.

I could solve it by removing the `@OneToMany` on the User class. Still not a satisfying fix, but i hope it helps.

**Comment by lipsumar** [comment]
this could help: https://github.com/typeorm/typeorm/issues/850#issuecomment-536455565

**Comment by vlapo** [comment]
Looks really like circular dependency issue. But it is problem with your environment. I do not see any way how to handle this in `class-validator` source code. Feel free open new issue in case you have some idea how to fix/handle this issue.
