### ISSUE TITLE
Is there any equivalent to isOptional() but that which also works for empty strings?

### ISSUE THREAD

**Issue by rohanfaiyazkhan** [typestack/class-validator#433]
I have a class where I am using:
```
@isOptional()
@isEmail
public email: string
```
However as it works currently the isEmail() validation is skipped only if the field is `null` or `undefined`. I would also like it to be skipped if the field is an empty string (""). Currently I am doing this using a custom class but is there any other way to achieve this?

**Comment by vlapo** [comment]
Hi, 
This was topic in the past - mostly because of security issue. (https://github.com/typestack/class-validator/pull/110,https://github.com/typestack/class-validator/issues/232)

Right now we do not have option to disallow empty strings. You should handle this in your codebase e.g. during transformation data from JSON to instance of class.

**Comment by rohanfaiyazkhan** [comment]
I see, thank you for the explanation.
