### ISSUE TITLE
Document if some decorators can be/are inferred through the type system

### ISSUE THREAD

**Issue by Lectem** [typestack/class-validator#659]
### Description

Sorry if it is a beginner question but I am quite new to the typescript ecosystem.
I find it unclear whether(why) some decorators are (or not) mandatory by looking at the documentation.

Are `IsString`, `IsNumber`, `IsBoolean` `IsOptional` needed?
What happens if some fields are not decorated?

And if those decorators can not be deduced implicitly, is it due to a limitation of typescript?

Thanks a lot

**class-validator version:** <code>0.12.2</code>

**Comment by josh18** [comment]
As far as I can tell nothing is inferred? I think if your property does not have a decorator that just means you don't want to validate that property.

**Comment by NoNameProvided** [comment]
> I find it unclear whether(why) some decorators are (or not) mandatory by looking at the documentation.

You must decorate all properties you want to check.

And if those decorators can not be deduced implicitly, is it due to a limitation of typescript?

We cannot infer types a 100% of the time so we are not doing it. (Eg: if a property has no decorator assigned TS compiler won't emit metadata for it.)
