### ISSUE TITLE
fix: IsPostalCode

### ISSUE THREAD

**Issue by Nesty92** [typestack/class-validator#784]
### Description
IsPostalCode in class-validator don't allow pass 'any' as a valid locale to check againts all types, check the validator docs
https://github.com/validatorjs/validator.js

### Expected behavior

isPostalCode('any')

### Actual behavior

Cannot pass 'any' as a valid locale

**Comment by mick352** [comment]
Has been fixed in develop. Just needs a merge and deploy.

**Comment by caiomestres** [comment]
@Nesty92 not really recommended but i just put in types/decorator/string/isPostalCode.d.ts 
export declare function IsPostalCode(locale?: validator.PostalCodeLocale | 'any', validationOptions?: ValidationOptions): PropertyDecorator;
repeat: not recommended since ur messing with node_modules, worked for me so for because I'm working solo.
@mick352 couldn't find the PR related to this, can you tell me, please?

**Comment by mick352** [comment]
See here: https://github.com/typestack/class-validator/commit/6bcae2f4ef9dba37798e89793f5408123c4f9ddb

Regards,
Michael Kreikenbaum

--
Web-Programmierung
Heise Medien GmbH & Co. KG                    Tel  +49 511 5352 217
Karl-Wiechert-Allee 10, 30625 Hannover        <mailto:mick@heise.de>

Registergericht: Amtsgericht Hannover HRA 26709

Persönlich haftende Gesellschafterin:
Heise Medien Geschäftsführung GmbH
Registergericht: Amtsgericht Hannover, HRB 60405
Geschäftsführer: Ansgar Heise, Dr. Alfons Schräder

On 27. Dec 2020, at 16:25, Caio Mestres <notifications@github.com<mailto:notifications@github.com>> wrote:



@Nesty92<https://github.com/Nesty92> not really recommended but i just put in types/decorator/string/isPostalCode.d.ts
export declare function IsPostalCode(locale?: validator.PostalCodeLocale | 'any', validationOptions?: ValidationOptions): PropertyDecorator;
repeat: not recommended since ur messing with node_modules, worked for me so for because I'm working solo.
@mick352<https://github.com/mick352> couldn't find the PR related to this, can you tell me, please?

**Comment by NoNameProvided** [comment]
Released as `0.13.0`.
